---
- name: Hello Events Forever
  hosts: all
  sources:
    - ansible.eda.tick:
        delay: 10
  rules:
    - name: Say Hello
      condition: event.i >= 1
      action:
        run_playbook:
          name: ansible.eda.hello
...
