---
- name: Hello Hostname
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 5
  rules:
    - name: get hostname
      condition: event.i == 1
      action:
        run_playbook:
          name: playbooks/hostname.yml
...
